apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default   # Add the namespace here
  labels:
    app: demo-voting-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: demo-voting-app
    name: postgres-pod
