apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: result-app-ingress
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`192.168.3.221.sslip.io`)
      priority: 10
      services:
        - name: result-service
          port: 80
