apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: result-app-ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`192.168.3.221.traefik.me`)
      kind: Rule
      services:
        - name: result-service
          port: 80
          