apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .values.name }}
  labels:
    name: {{ .values.appName }}
    app: {{ .values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .values.name }}
      app: {{ .values.appName }}
  template:
    metadata:
      name: {{ .values.name }}
      labels:
        name: {{ .values.name }}
        app: {{ .values.appName }}
    spec:
      containers:
      - name: {{ .values.name }}
        image: "{{ .values.image.name }}:{{ .values.image.tag }}"
        ports:
        - containerPort: 80

