apiVersion: v1
kind: Service
metadata:
  name: {{ .values.name }}
  labels:
    name: {{ .values.name }}
    app: {{ .values.appName }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    name: {{ .values.name }}
    app: {{ .values.appName }}