apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingName }}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`192.168.3.221.nip.io`)
      priority: 10
      services:
        - name: {{ .Values.name }}
          port: 80